### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yuriy-yarosh** [rpxpx/OpenVSP_pkgbuild#1]
There's a typo [over here](https://github.com/rpxpx/OpenVSP_pkgbuild/commit/d13218792852193c7245377c7e2cec13167f787f#diff-c13dbcca92f9ff12cd26ecce958be3f9ee8563baace04f7a463a6d2dd4252e0bR94)

**Comment by rpxpx** [comment]
thank you! fixed it
